spring.application.name=goooogle

# SQLite datasource
spring.datasource.url=jdbc:sqlite:./goooogle.db
spring.datasource.driver-class-name=org.sqlite.JDBC

management.endpoints.jmx.exposure.include=*
management.endpoints.web.base-path=/status
spring.devtools.livereload.enabled=true